### PR TITLE
Add SECURITY.md

### LINKED ISSUE #584: Adopt a security policy
We should adopt a security policy for Junction, something like a `SECURITY.md` file. The essential points that need to be outlined in it are:

- Rules of engagement (like don't test on prod!)
- What counts as a bug (it could be a feature :))
- Reporting a bug (who to contact, report template)

This is in relation to #583, which I wasn't too happy about reporting via an issue, but I didn't know better.

Thoughts?

### PR DESCRIPTION
**Pull request by icyphox**
Fixes #584 

This PR is up for debate/discussion. What else needs to be added to this?  
Also, we need an email to receive reports.

### CODE REVIEW

**Comment by icyphox** [comment]
> This should live in the documentation as the "security policy" page.

I'm not sure I agree. The security policy for the project should be easily noticeable and not some page hidden away in the docs.

> You'll probably want to note that security issues should not be filed publicly and sent via email to the developers/maintainers (ideally by providing an email here).

Agreed, I'll add this in. I've also mentioned the need for an email to receive reports in the first comment.

> The language of the "reporting a bug" seems to be more in line with something for the contributing guide.

Well, it's the standard format followed by platforms like HackerOne, for reports. I figured it'd fit in here as well. What do you suggest?

> Further, it references the use of email and a security team, which haven't been mentioned in the rest of the document.

Yeah, again, we'll need an email from Junction's maintainers. /cc @zerothabhishek

**Comment by pradyunsg** [comment]
> The security policy for the project should be easily noticeable and not some page hidden away in the docs.

Would the way [Django] and [PyPI] handle their security policy serve as enough prior art to justify my position? Neither store it the root of the project's repository.

[Django]: https://github.com/django/django/blob/master/docs/internals/security.txt
[PyPI]: https://github.com/pypa/warehouse/blob/master/warehouse/templates/pages/security.html

> What do you suggest?

Something like what Django does, should be good enough for us:

```
Short version: please report security issues by emailing security@<somewhere>.com.

Most normal bugs in Junction are reported to our public GitHub issue tracker, but due to the sensitive nature of security issues, we ask that they not be publicly reported in this fashion.

Instead, if you believe you’ve found something in Junction which has security implications, please send a description of the issue via email to security@<somewhere>.com. Mail sent to that address reach a security team.
```

I think it is also important to note that given that this project does not have any active maintainers, it's probably better to not promise a timeline for a response to the reporter.

**Comment by icyphox** [comment]
> Would the way Django and PyPI handle their security policy serve as enough prior art to justify my position? Neither store it the root of the project's repository.

Fair enough. In that case, I'll close this PR and you can proceed to add the security policy over at #577.

> Something like what Django does, should be good enough for us:
> ...

LGTM.

> I think it is also important to note that given that this project does not have any active maintainers, it's probably better to not promise a timeline for a response to the reporter.

Let's wait on @zerothabhishek for a final take.

**Comment by pradyunsg** [comment]
> Fair enough. In that case, I'll close this PR and you can proceed to add the security policy over at #577.

Yea, either of us can add it in a follow up PR to #577. I don't want that to be held up due to a discussion on the exact security policy we end up with.

**Comment by ananyo2012** [comment]
@palnabarun We should create a email alias via magudi for reporting security issues. Then we can proceed with the documentation. Can you keep it as an action item when you update the PyCon 2020 email aliases in magudi ?

**Comment by palnabarun** [comment]
Sure. :+1:

**Comment by ananyo2012** [comment]
Let's go ahead with webmaster@in.pycon.org which I believe exists already. @pradyunsg You may want to add a `SECURITY.rst` when you update the documentation.

**Comment by pradyunsg** [comment]
Closing since #584 is the tracking issue and we're going to be taking a different approach for documenting our security policy (in the built documentation vs as a security.md file).

**Pull request closed without merging**
