### PR TITLE
Updated code for Python 2 to 3 refactoring

### LINKED ISSUE #316: Migrate to Python 3
As @theskumar [mentioned](https://github.com/pythonindia/junction/issues/201#issuecomment-90929480),  we can move to Python 3 and drop  support for Python  2.

### PR DESCRIPTION
**Pull request by Akasurde**
Fixes #316 
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by Akasurde** [comment]
Ping

**Comment by kracekumar** [comment]
Apologies for not responding and Thanks for reminding. I will provide further comments from next week onwards.

**Comment by ChillarAnand** [comment]
If we are moving to Python 3, we can [drop support for Python 2](https://github.com/pythonindia/junction/issues/316#issue-96104625).

**Comment by kracekumar** [comment]
We will move, but we need to move without breaking backward changes. One
shoot rewrite may be bad idea.

On Mon, Dec 7, 2015 at 8:30 PM, Anand Reddy Pandikunta <
notifications@github.com> wrote:

> If we are moving to Python 3, we can drop support for Python 2
> <https://github.com/pythonindia/junction/issues/316#issue-96104625>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/pull/373#issuecomment-162548962>.
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Comment by Akasurde** [comment]
@kracekumar I agree with you. This pull request can be start of conversion then.

**Comment by kracekumar** [comment]
@Akasurde Can you enable `py3.4, py3.5` test support in travis ?

**Comment by Akasurde** [comment]
@kracekumar Yes, I will add and update this PR

**Comment by Akasurde** [comment]
Tracking using PR #379

**Pull request closed without merging**
