### PR TITLE
Added Sub tabs and moved coc page inside the about tab

### PR DESCRIPTION
**Pull request by vnbang2003**
Added Sub tabs and moved coc page inside the about tab

### CODE REVIEW

**Comment by vnbang2003** [comment]
Can someone review this changes.

**Comment by theskumar** [comment]
@sivaa can you please do a review. I am not sure if we would like to merge this now. 

@vnbang2003, @sivaa will have the final say regarding this PR.

**Comment by sivaa** [comment]
@vnbang2003 I will take care of this request during this week-end since some cleanup & resolving merge conflict is required.

**Comment by sivaa** [comment]
@vnbang2003 We will not integrate this pull request at this moment. But whenever the individual static page comes, we will use the appropriate menu as mentioned in this PR.

**Comment by sivaa** [comment]
Closing this PR since we will add a single static page as discussed over the mail. @vnbang2003 will takes care of the content.

**Pull request closed without merging**
