### PR TITLE
Remove uwsgi from application dependencies

### LINKED ISSUE #651: Issue while setting up in windows 10
Python version: 3.5 
Windows 10 Pro, version:  1903

While running **nox -- migrate --noinput** for the first time, we are getting an issue saying 
**AttributeError: module 'os' has no attribute 'uname'**

With quick googling, I could figure out that this is related to the package **uwsgi==2.0.*** in the **requirements.txt**

I removed this package from requirements.txt and tried running the command again and it worked. 

Everything seems to work fine after this also. I am not sure about the purpose of this package, so I thought of putting this as an issue here. 
 
Thanks,

### PR DESCRIPTION
**Pull request by palnabarun**
uwsgi is installed by default using other means in the virtualenv
used by junction. There is no need to install uwsgi through the
application dependencies.

The support for uwsgi is flaky at best on Windows and works with
very limited functionality. Hence, this breaks development velocity
for people developing Junction on Windows.

Ref: #651

Closes #651

### CODE REVIEW

**Comment by palnabarun** [comment]
Closing and reopening for satisfying Travis CI. :disappointed:

**Comment by sayanchowdhury** [comment]
Just a wild guess, but won't squashing an empty commit also trigger the CI?

**Comment by palnabarun** [comment]
@sayanchowdhury -- It should even if I amend the commits and force push. The problem is with Travis CI not even getting the events. :man_shrugging:

**Comment by sayanchowdhury** [comment]
Hmm, weird.

**Comment by ananyo2012** [comment]
@palnabarun I think it will be good to move this to a separate `requirements-prod.txt` until we have a proper dependency management tool.

**Comment by palnabarun** [comment]
> I think it will be good to move this to a separate requirements-prod.txt until we have a proper dependency management tool.

Well, uwsgi is going to go away soon in the new setup. uwsgi is not related to the Junction application and should not be there in the project at all.

**Comment by ananyo2012** [comment]
Isn't uswgi needed in production ?

**Comment by palnabarun** [comment]
> Isn't uswgi needed in production ?

Yes. It is, but not installed using this project's requirements.

**Comment by ananyo2012** [comment]
Well it's good to have a separate prod-requirements.txt than to manually install production packages

**Comment by ananyo2012** [comment]
Keeping all dependencies in requirements.txt for now to ease dev and prod installs.

**Pull request closed without merging**
