### PR TITLE
try running python tests under python3 and pypy

### PR DESCRIPTION
**Pull request by vigneshsarma**
Should help with #362 ,
Also py3k.

cc: @ChillarAnand

### CODE REVIEW

**Comment by ChillarAnand** [comment]
Compatibility for pyscopyg2cffi?

```
from psycopg2cffi import compat
compat.register()
```

**Comment by kracekumar** [comment]
Can you rebase ?

**Comment by sivaa** [comment]
@vigneshsarma Are we still considering this PR?

**Comment by ChillarAnand** [comment]
As we [have tested earlier](https://github.com/pythonindia/junction/issues/362#issuecomment-150935432), junction runs twice as slower with pypy. I dont think pypy provides any extra performance for a normal CRUD web.

**Comment by sivaa** [comment]
Can we close this PR?

**Comment by ChillarAnand** [comment]
Sure. If any one comes up with a better performance with pypy or any other implementation, feel free to reopen.

**Pull request closed without merging**
