### PR TITLE
fix flake8 errors

### PR DESCRIPTION
**Pull request by ChillarAnand**

### CODE REVIEW

**Comment by kracekumar** [comment]
@vnbang2003 Looks like the dashboard is viewable to everyone. Was this intentional ?

@ChillarAnand made it visible only to reviewers. I am not convinced about showing dashboard to reviewers also. I feel this should be visible to organizing committee.

**Comment by theskumar** [comment]
@ChillarAnand can you please rebase your work/branch on top of the current master. seems like we are getting merge conflict here.

**Comment by ChillarAnand** [comment]
@theskumar updated

**Comment by ChillarAnand** [comment]
closes #241

**Pull request merged**
