### PR TITLE
Fixes 404 Error on conference index url

### LINKED ISSUE #558: The parent URL of cfp page should not give 404
The URL of the CFP page for PyCon India 2017 is:

https://in.pycon.org/cfp/2017/proposals/

If you look at one level up, the URL <https://in.pycon.org/cfp/2017> gives `404`. It is generally good practice to make sure the parent either has thing to show or redirect to appropriate page.

In this case, it would be better to redirect to `proposals/` page instead of showing 404.

### PR DESCRIPTION
**Pull request by realslimshanky**
This fixes #558 
Please review @pythonindia/pycon-2018-team

### CODE REVIEW

**Comment by palnabarun** [comment]
This looks good to me!

**Comment by palnabarun** [comment]
@ananyo2012 What do you think?

**Comment by ananyo2012** [comment]
I am a bit skeptical about regexes, let's test this out once before merging.

**Comment by palnabarun** [comment]
I have tested it locally and it works.

**Comment by palnabarun** [comment]
We can go ahead with this.

**Pull request merged**
