### PR TITLE
Added Tickets app

### PR DESCRIPTION
**Pull request by ChillarAnand**

### CODE REVIEW

**Comment by ChillarAnand** [comment]
Set explara  api token, path to qr codes and run `sync_data` management command.

**Comment by kracekumar** [comment]
Can we have Admin UI to trigger the same ? It is easier to give access to admin UI rather than server.

**Comment by ChillarAnand** [comment]
Added UI to sync data.

**Comment by kracekumar** [comment]
Oh rebase!

**Comment by kracekumar** [comment]
Will merge sometime tomorrow.

**Pull request merged**
