### PR TITLE
Django version upgraded from 1.8 to 1.9

### PR DESCRIPTION
**Pull request by cosmologist10**

### CODE REVIEW

**Comment by kracekumar** [comment]
@cosmologist10 Can you fix the failing test case?

**Comment by cosmologist10** [comment]
@kracekumar I have updated the version, please check the functionality.

**Comment by kracekumar** [comment]
@cosmologist10 Did you get a chance to address suggestion on `settings/common.py`? After amending those changes, it's good to merge.

**Comment by cosmologist10** [comment]
I didn't get u.

**Comment by cosmologist10** [comment]
@kracekumar, have a look on the changes done as per review

**Comment by kracekumar** [comment]
@cosmologist10 :+1:

**Comment by cosmologist10** [comment]
Thanks :)

On 12-Apr-2017 1:14 am, "R.Kracekumar" <notifications@github.com> wrote:

Merged #522 <https://github.com/pythonindia/junction/pull/522>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pythonindia/junction/pull/522#event-1038988250>, or mute
the thread

**Pull request merged**
