### PR TITLE
Use responsive template for sending comment mails

### PR DESCRIPTION
**Pull request by ChillarAnand**
Preview

j

### CODE REVIEW

**Comment by theskumar** [comment]
Well, this isn't going to work out in different email clients, the css need to be inlined either manually or via script during runtime. prefixer is good stuff you can use. 

Also, it's nice to have a base email template and then extend for the actually email.

**Comment by ChillarAnand** [comment]
cc

**Comment by kracekumar** [comment]
"Click here to login and leave a comment" can be renamed to "Click here to leave a comment".

Also, when a new proposal is submitted, reviewers get a email. Can we use same template for it ?

**Comment by ChillarAnand** [comment]
ee

**Pull request merged**
