### PR TITLE
Update requests to 2.20.0

### PR DESCRIPTION
**Pull request by palnabarun**
Ref: https://github.com/pythonindia/junction/network/alerts

### CODE REVIEW

**Comment by ananyo2012** [comment]
@palnabarun Can you upgrade all the dependencies at one go which are not blocked by the django version ?

**Comment by palnabarun** [comment]
@ananyo2012 It was just a security update. I was looking at the alerts given out by Github. I will incrementally update each dependency in a separate PR. :)

**Comment by pradyunsg** [comment]
Can we handle this as part of a broader dependency upgrade step, that includes upgrading to a newer, supported version of Django?

We're already using Django 1.9 (not even the patch versions) so it's not like this is going to suddenly improve security for us.

**Comment by palnabarun** [comment]
@pradyunsg I don't think a broad change blocker should block a security alert which we are getting to our face.

While I am in agreement that this small change may change things at minimal, but there is no plausible reason to not do it one by one.

**Comment by ananyo2012** [comment]
I propose we merge this in since it's better off holding.

**Comment by pradyunsg** [comment]
I didn't mean to unilaterally block this change from being merged. If that's what I wanted, I would've stated that explicitly. :)

I've gone ahead and merged it in since this silences a security advisory that GitHub issued. I also get a 404 on the link that @palnabarun provided in OP, so 🤷‍♂.

To reiterate, there isn't any significant benefit to just because we merged this, because we're on a version of Django (without *any bug fix releases*) that has been EOL for 3 years now. The entire 1.x series is EoL now, including the LTS release of 1.11.

Django doesn't even show it in [the diagram for supported versions anymore](https://www.djangoproject.com/download/#supported-versions).

**Comment by ananyo2012** [comment]
Yes sure let's move our priority on the Django 2 upgrade now which has the
next LTS.

**Pull request merged**
