### PR TITLE
Delete .gitattributes

### PR DESCRIPTION
**Pull request by pradyunsg**
The current configuration doesn't add much value, and I'm all for removing unnecessary files from a repository.

### CODE REVIEW

**Comment by ananyo2012** [comment]
@pradyunsg This is handling line endings for Windows to convert to LF. It's good to have

**Comment by palnabarun** [comment]
Shouldn't the folks have it configured in their text editor?

**Comment by ananyo2012** [comment]
Well lot of people do not. So to safeguard it it's used. But there is also a `.editorconfig` file I see where line ending is set to LF.

**Comment by palnabarun** [comment]
I see that `.editorconfig` by a lot of [editors](https://editorconfig.org/). Shall we deprecate `.gitattributes` in favor of `.editorconfig`?

**Pull request merged**
