### PR TITLE
Issue #366 solved, user is able to connect twitter facebook and linkedin

### PR DESCRIPTION
**Pull request by shashankaryan**

### CODE REVIEW

**Comment by kracekumar** [comment]
@shashankaryan Thanks for adding twitter, facebook, LinkedIn support. Could you share a screenshot how the login page looks?

The tests are broken and nothing to do with your PR. Would you be interested in fixing them?

**Comment by shashankaryan** [comment]
screenshot_20170106_192733

**Comment by shashankaryan** [comment]
@kracekumar how is this page looking?

**Comment by kracekumar** [comment]
@shashankaryan It looks buttons alignments are misplaced. Can you take care of spacing between Google and GitHub button? GitHub button is out of place. Order of button should be Google, GitHub, Twitter, Facebook, LinkedIn.

Also, you may add links to add create app in each one of the sites in README file.

**Comment by kracekumar** [comment]
@shashankaryan Any update?

**Comment by pythonhacker** [comment]
Pls merge the changes after verifying.

**Comment by pythonhacker** [comment]
Thanks Krace.

**Comment by shashankaryan** [comment]
Thanks @kracekumar

**Pull request merged**
