### PR TITLE
Added Python 2 to 3 changes

### LINKED ISSUE #316: Migrate to Python 3
As @theskumar [mentioned](https://github.com/pythonindia/junction/issues/201#issuecomment-90929480),  we can move to Python 3 and drop  support for Python  2.

### PR DESCRIPTION
**Pull request by Akasurde**
Fixes #316 
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by kracekumar** [comment]
@Akasurde Test Case for `3.4` and `3.5` are failing. Can you fix it ?

**Comment by Akasurde** [comment]
@kracekumar Yes I am checking

**Comment by Akasurde** [comment]
Removed Python 3.5 related travis config as Django 1.7.8 and Python 3.5 are not compatible.

**Comment by kracekumar** [comment]
@Akasurde Feel free to look for changes and send us a pull request.

**Comment by Akasurde** [comment]
@kracekumar Thanks. Sure.

**Pull request merged**
