### PR TITLE
add proposal type and section in list of proposals

### PR DESCRIPTION
**Pull request by geetanjaligg**

### CODE REVIEW

**Comment by kracekumar** [comment]
@geetanjaligg Your pull request has flask8 issue, can you fix it ? Also can you attach a screen shot ?

**Comment by ChillarAnand** [comment]
@kracekumar  close this?

**Comment by kracekumar** [comment]
Thanks for the pull request. This is already fixed.

**Comment by geetanjaligg** [comment]
Cool! 
I wasn't active for a while. I missed this thread.

**Pull request closed without merging**
