### PR TITLE
Refactor conference status as Enum

### PR DESCRIPTION
**Pull request by dhilipsiva**
Do NOT merge this, yet!

Few days back, I opened #302 To discuss this refactor. Makes code base a bit more readable. So far, I have refactored only `Conference.status` to adopt this. If this seems favourable, I will continue refactoring other choices field too. Else lets close this PR.

@kracekumar I know you weighed-in favourable. But just confirming once more.

[Review on Reviewable](https://reviewable.io/reviews/pythonindia/junction/308)

### CODE REVIEW

**Comment by kracekumar** [comment]
Let's wrap this up ?

**Comment by dhilipsiva** [comment]
Oh, I was waiting for your opinion. If it looks favourable, please let me know, I will push commits for all the other choices too. Else lets close this PR.

**Comment by kracekumar** [comment]
Ok, we can go with `_` convention.

**Comment by dhilipsiva** [comment]
Okies. In that case, I will send you a PR tonight.

--

dhilipsiva  

Full Stack & DevOps Engineer.

Website : http://dhilipsiva.com
Github : https://github.com/dhilipsiva
Twitter : https://twitter.com/dhilipsiva
Email : dhilipsiva@gmail.com
Mobile : +91 81977 93582

On 22 July 2015 at 15:42:19, Kracekumar Ramaraju (notifications@github.com) wrote:

Ok, we can go with _ convention.

**Comment by dhilipsiva** [comment]
@kracekumar We can merge this now. Lets merge it before there are more conflicts :stuck_out_tongue:

**Pull request merged**
