### PR TITLE
Fix deprecations: Round 1

### PR DESCRIPTION
**Pull request by pradyunsg**

### CODE REVIEW

**Comment by pradyunsg** [comment]
> 369 warnings

*sigh* This is gonna take a while.

**Comment by palnabarun** [comment]
@pradyunsg I think it would be a better idea for new contributors to start fixing the deprecation warnings. Through that, they can get started on how junction is structured. Can you create an Umbrella issue with all the warnings?

**Comment by ananyo2012** [comment]
What are these warnings? And when are we able to see those ?

**Comment by pradyunsg** [comment]
They show up if you run the tests locally.

These were a little more involved. There are a few that are from our dependencies (which need to be upgraded) and a whole lot from needing to specify on_deleye behaviors.

I welcome someone to help with the second but, as well as to file an umbrella issue.

**Comment by sks444** [comment]
@ananyo2012  we can also run `python -Wall manage.py runserver` to see all the deprecated warnings. Removing these will help us in upgrading Django to 2/3.

@pradyunsg I can help out the `on_delete` warnings.

**Comment by ananyo2012** [comment]
@pradyunsg Are these changes ready ?

**Comment by pradyunsg** [comment]
Yup!

**Pull request merged**
