### PR TITLE
All urls.py are consistent in naming

### PR DESCRIPTION
**Pull request by theSage21**
Urls.py previously proposal_urls.py and comment_urls.py are now in a single file proposals/urls.py
Also the url /proposal-comments has been changed to /proposals/comments

### CODE REVIEW

**Comment by kracekumar** [comment]
Can you fix the failing test ?

**Comment by theSage21** [comment]
i did not think tests would fail. there were none dependent on the urls. Ill try though i have little experience there.

**Comment by ChillarAnand** [comment]
@theSage21 thansk for pr.
looks like `include`  was not  imported in  urls.py.
also  make sure you run `flake8`  before submitting PR.

**Comment by theSage21** [comment]
@ChillarAnand Will do. Leave it to me. thanks for the opportunity.

**Comment by theSage21** [comment]
That should do it. flake8 shows beauty errors but thats fine i guess. Functional.

**Comment by theSage21** [comment]
All tests pass and flake8 passes. There is one flake8 error which I do not understand so I have not touched it. Rest is fixed.

**Comment by theSage21** [comment]
someone pull?

**Comment by kracekumar** [comment]
@theSage21 Can you rebase ?

**Comment by theSage21** [comment]
@kracekumar First time using rebase.
git checkout consistent_urls
git rebase master
git checkout master
git merge consistent_urls
git push origin master

Done those commands. Is that all I need to do?

**Comment by kracekumar** [comment]
It is simple. 

- `git checkout master`
- `git pull -r`
- `git checkout <your_branch>`
- `git merge master`
- `git push -u origin <your_branch>`

**Comment by theSage21** [comment]
@kracekumar Al right. I have executed those commands

**Comment by kracekumar** [comment]
@theSage21 Still Github UI say's I can't merge. See if this helps https://dont-be-afraid-to-commit.readthedocs.org/en/latest/git/conflicts.html

**Comment by theSage21** [comment]
@kracekumar I give up. I do not understand what is happening. Sould I close this PR and reclone and start from scratch? maybe that should help?

**Comment by theSage21** [comment]
@kracekumar I have opened a new pull request. https://github.com/pythonindia/junction/pull/238

**Pull request closed without merging**
