### PR TITLE
Conference admin control

### LINKED ISSUE #403: Conference admin control
Currently Django admin is used to control all `conference, reviewers, feedback questions, reviewer internal questions`. Site admin is allowed to manage all these features. Every year conference admins are different. Conference admin should be allowed to add new `reviewers`, configure `questions` rather than site admin. Site admin should be allowed to change details across conference.

Admin site requires ACL depending on conference. Django admin or custom UI can be used. Django admin UI is customisable and using existing UI will save lot of time.

@ChillarAnand can you work on it ?

### PR DESCRIPTION
**Pull request by ChillarAnand**
closes #403 

jj

jj2

@kracekumar checkout

### CODE REVIEW

**Comment by kracekumar** [comment]
So this lets `moderator` to view conference related objects but doesn't solve the problem yet. Say `A` is part of 2015 conference, `B` is part of 2016 conference and `A` is part of 2017 conference. `A` shouldn't have access to 2016 settings and `B` shouldn't see 2015 and 2017 conference settings. The current code lets `A` and `B` to view all three conference settings. Correct me if I am wrong.

**Comment by ChillarAnand** [comment]
Yes, you are right. For that we need to implement row level/object level permissions.

**Comment by kracekumar** [comment]
Yes. Let's do that ?

On Mon, Mar 7, 2016 at 12:15 PM, Anand Pandikunta <notifications@github.com>
wrote:

> Yes, you are right. For that we need to implement row level/object level
> permissions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/pull/412#issuecomment-193126574>.
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Comment by ChillarAnand** [comment]
Row level permissions seems too much for this task. Will [filtering queryset suffice](https://github.com/ChillarAnand/junction/blob/master/junction/conferences/admin.py#L25-L31)?

**Comment by ChillarAnand** [comment]
fixed in #414

**Pull request closed without merging**
