### PR TITLE
enhancements for proposals to review page

### PR DESCRIPTION
**Pull request by ChillarAnand**
enhancements for proposals to review page [as mentioned here](https://github.com/pythonindia/junction/pull/295#issuecomment-117810194)

### CODE REVIEW

**Comment by ChillarAnand** [comment]
forgot to attach screenshot. duh :) 

fi

**Comment by kracekumar** [comment]
I am leaning to write this in Python now ;-) JS doesn't seem to work right.
Say select Proposal type as "Workshop" and Reviewer Comment as "No".
Applying filter shows  Talks also :-) Let me double check.

On Thu, Jul 2, 2015 at 10:13 PM, Anand Reddy Pandikunta <
notifications@github.com> wrote:

> forgot to attach screenshot. duh :)
>
> [image: fi]
> <https://cloud.githubusercontent.com/assets/4463796/8482486/90083046-2107-11e5-8471-68058208a158.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/pull/297#issuecomment-118089582>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by kracekumar** [comment]
Anand, I tried in js to get right behaviour but DOM hiding and reapply
didn't work.

Can we move this to server side ? We will support filter by multiple query
strings.
When more than one query string is sent, we do `and` filter in proposal qs.
What do you think ?

I am extremely sorry sloppy decision.

On Thu, Jul 2, 2015 at 10:24 PM, Kracekumar Ramaraju <me@kracekumar.com>
wrote:

> I am leaning to write this in Python now ;-) JS doesn't seem to work
> right. Say select Proposal type as "Workshop" and Reviewer Comment as "No".
> Applying filter shows  Talks also :-) Let me double check.
>
> On Thu, Jul 2, 2015 at 10:13 PM, Anand Reddy Pandikunta <
> notifications@github.com> wrote:
>
>> forgot to attach screenshot. duh :)
>>
>> [image: fi]
>> <https://cloud.githubusercontent.com/assets/4463796/8482486/90083046-2107-11e5-8471-68058208a158.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pythonindia/junction/pull/297#issuecomment-118089582>
>> .
>>
>
>
>
> --
> Regards
> Kracekumar Ramaraju
> http://kracekumar.com
> +91 85530 29521
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by ChillarAnand** [comment]
@kracekumar Sorry for the delay. I was away this weekend.

As Mudassir pointed out, we have to use backbone.js or stick with server side filtering.

**Comment by kracekumar** [comment]
As of now we will stick with server side :-)

On Mon, Jul 6, 2015 at 6:46 PM, Anand Reddy Pandikunta <
notifications@github.com> wrote:

> @kracekumar <https://github.com/kracekumar> Sorry for the delay. I was
> away this weekend.
>
> As Mudassir pointed out, we have to use backbone.js or stick with server
> side filtering.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/pull/297#issuecomment-118851671>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Pull request merged**
