### PR TITLE
added proposals to review page

### PR DESCRIPTION
**Pull request by ChillarAnand**
front end filtering is not yet implemented.

screenshots

r1

r2

### CODE REVIEW

**Comment by kracekumar** [comment]
What about filtering ? Other stuff looks good :+1:

**Comment by ChillarAnand** [comment]
Not familiar with js. Will checkout tomorrow.

**Comment by kracekumar** [comment]
sure. It should be easy with jquery.

On Wed, Jul 1, 2015 at 12:40 AM, Anand Reddy Pandikunta <
notifications@github.com> wrote:

> Not familiar with js. Will checkout tomorrow.
> On 01/07/2015 12:18 am, "Kracekumar Ramaraju" <notifications@github.com>
> wrote:
>
> > What about filtering ? Other stuff looks good [image: :+1:]
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pythonindia/junction/pull/295#issuecomment-117299459
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/pull/295#issuecomment-117308859>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by ChillarAnand** [comment]
screenshot:
fil

@kracekumar  let me know if any changes are required

closes #256

**Comment by kracekumar** [comment]
@ChillarAnand Few issues. 

- The drop down should allow unselected values. Let's say I want to filter all proposals which has no `review comments`. Current one forces to select options from all three drop down box.
- Let's say I choose `web development` in drop down and apply filter, it displays all the results. Now I need to go back to previous state without any filter. As of now I need to reload the page. We can small `x` near filter to remove all applied filter which can simply reload the current page.
- `Left a Review Comment` currently uses `has_reviewer_comments`, which checks there is atleast one review comment, actual behaviour should check that current user should have left the comment. If `Reviewer A` has left a comment and `Reviewer B` shouldn't see `Left a Review Comment`.

**Pull request merged**
