### PR TITLE
Added highligthing in base.html

### PR DESCRIPTION
**Pull request by Aayush-Kasurde**
Fixes issue #138

### CODE REVIEW

**Comment by ChillarAnand** [comment]
can you attach a screenshot please?

**Comment by Aayush-Kasurde** [comment]
@ChillarAnand - Here is screenshot
junction_fix

**Comment by ChillarAnand** [comment]
@kracekumar  @theskumar close this or request for an update?

**Comment by kracekumar** [comment]
@ChillarAnand We can merge. @Aayush-Kasurde sorry for the delay. Can you rebase and push ? I will merge.

**Comment by Aayush-Kasurde** [comment]
@ChillarAnand @kracekumar I can rebase and push again. Thanks.

**Comment by ChillarAnand** [comment]
@Aayush-Kasurde  add yourself to [contributors](https://github.com/pythonindia/junction/blob/master/CONTRIBUTORS.txt) list

**Comment by Aayush-Kasurde** [comment]
Closing and tracking using PR #232

**Pull request closed without merging**
