### PR TITLE
Fix issue(#714) with voting proposal.

### PR DESCRIPTION
**Pull request by RajatRajdeep**
This PR fixes following issue: https://github.com/pythonindia/junction/issues/714

### CODE REVIEW

**Comment by RajatRajdeep** [comment]
Hi @ananyo2012, I think this change is not yet merged. Could you review this?

**Comment by RajatRajdeep** [comment]
Hi @ananyo2012, These changes are not merged. Could you review and reopen the PR?

**Comment by ananyo2012** [comment]
@RajatRajdeep Please raise this PR against master now. feature branch is merged to master now.

**Comment by RajatRajdeep** [comment]
@ananyo2012 Please reopen it so I can change the target branch.
Not able to modify the closed PR.

**Comment by ananyo2012** [comment]
I already tried editing the PR. It doesn’t work. Please raise a new PR.

**Comment by RajatRajdeep** [comment]
Okay, I'll raise another one.

**Comment by gurpreetkaur2309** [comment]
have you solved the issue?

**Pull request closed without merging**
