### PR TITLE
Update details.css

### PR DESCRIPTION
**Pull request by geetanjaligg**
Resolves https://github.com/pythonindia/junction/issues/93

Ignore the last pull request. Unwanted file commit.

### CODE REVIEW

**Comment by ChillarAnand** [comment]
Thanks for the PR.
Can you attach a screenshot please?

**Comment by geetanjaligg** [comment]
screenshot from 2015-01-29 13 13 23

**Comment by sivaa** [comment]
Can we close this pull request since it is already fixed? @kracekumar @mudassir0909

**Comment by mudassir0909** [comment]
Yes it can be closed

**Pull request closed without merging**
