### PR TITLE
added proposal type, section to proposal list.

### LINKED ISSUE #63: Proposal list page should contain information about Proposal Type and Section

### PR DESCRIPTION
**Pull request by ChillarAnand**
resolves #63

### CODE REVIEW

**Comment by kracekumar** [comment]
Can I have a screen shot please ?

**Comment by ChillarAnand** [comment]
jun

**Comment by kracekumar** [comment]
Proposal Type, scetion is bold in the image, but not exactly same in http://junction.pybelgaum.org/pybelgaum/proposals/, Am i missing something ?

**Comment by ChillarAnand** [comment]
Looks similar?

jj

**Comment by kracekumar** [comment]
Yea, sorry my bad :-(

**Pull request merged**
