### PR TITLE
Send mail to proposal author for proposal content

### LINKED ISSUE #162: Add custom admin action to proposals
Define a custom admin action for proposal objects which trigger emails for
1) request to upload content.
2) Talk status change email on state change.

### PR DESCRIPTION
**Pull request by ChillarAnand**
I have added sample message. Please update it as required.

Screenshots:

con1

con2

closes  #162

### CODE REVIEW

**Comment by kracekumar** [comment]
We need to have generic way of sending email to proposer for different reasons. Now I am merging this, we will rework later.

**Comment by kracekumar** [comment]
@vigneshsarma Deploy ?

**Comment by vigneshsarma** [comment]
Deployed.

**Comment by vnbang2003** [comment]
@ChillarAnand @kracekumar  who all can see button ?

**Comment by ChillarAnand** [comment]
@vnbang2003  Both reviewers & superusers can see button. As of now, we dont have tracking.

**Comment by ChillarAnand** [comment]
> We need to have generic way of sending email to proposer for different reasons. 

@kracekumar  Generic way? Should we have a form where reviewer can enter custom messages?

**Comment by kracekumar** [comment]
Yes. We will have list of messages type and templates, say "Request for
content", " Talk selected", "Talk rejected", " Schedule published " and
message area will populate the data. Reviewer/Admin can edit and send
email. We should log the email sent info.

**Comment by vnbang2003** [comment]
@ChillarAnand If we don't track it might happen that 2 reviewers click button or same reviewers himself will click button . I think junction should not end up as spam emailer.
We need to fix. Let me know if new tickets need to opened

**Comment by vnbang2003** [comment]
I see button is display even if content url is given. Is it expected behavior ?
upload_content

**Comment by kracekumar** [comment]
This wasn't mentioned in the initial conversation. We should check whether
content exists, if not show the button. If we migrate to generic mailing
approach we will move this to separate place.
We should also list of emails sent to proposer like log at the bottom only
visible to reviewers and admin.

You can open two issues, one for hiding the button if content uploaded,
migrate to generic email sending approach.

It would be better you can drop an line in the issue before working so that
expected behaviour can be said in advance :-)

On Wed, Jul 8, 2015 at 8:49 PM, Vijay <notifications@github.com> wrote:

> I see button is display even if content url is given. Is it expected
> behavior ?
> [image: upload_content]
> <https://cloud.githubusercontent.com/assets/316253/8574152/dbf9e9cc-25b2-11e5-9983-dac7e7d488fc.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/pull/301#issuecomment-119622992>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by vnbang2003** [comment]
@ChillarAnand Can you open tickets and keep this ticket are reference
We basically need 3 tickets
1) hiding the button if content uploaded
2) Show last remainder sent email to avoid duplicates
3) Migrate to generic emails.

**Comment by ChillarAnand** [comment]
u2

This proposal has some content in content urls section. But it doesn't have any urls or relevant slides.

u1

This porposal has urls but that urls doesn't have any relevant content or slides.

We do have lots of proposals like this in junction. It is quite difficult to programatically detect whether relevant content/slides are present in content urls. That is the reason for showing that button in all proposals.

**Comment by vnbang2003** [comment]
Good point . We need to find best way to fix this.

**Pull request merged**
