### PR TITLE
UI changes for Review Proposal & other minor things

### PR DESCRIPTION
**Pull request by mudassir0909**
* Made comment timestamp link muted so that it doesn't grab much attention. Repositioned author at the bottom since the comment is more important than who has commented
screen shot 2015-02-22 at 2 11 48 am
* Restyled proposal tags & added a separator above "review" link
screen shot 2015-02-22 at 2 11 25 am
* Added cancel button on comments form
screen shot 2015-02-22 at 2 12 07 am
* Restyled review proposal form
screen shot 2015-03-06 at 5 16 53 pm

### CODE REVIEW

**Comment by mudassir0909** [comment]
@ChillarAnand Can we render the review form manually instead of using `{% bootstrap_form proposal_review_form %}`, I'm trying to use a horizontal form by specifying 
```django
{% bootstrap_form proposal_review_form layout="horizontal" %}
```
but this automatically adds `.col-md-2` onto the label which I'd like to change.

**Comment by ChillarAnand** [comment]
sure.

**Comment by kracekumar** [comment]
Can this be merged ?

**Comment by sivaa** [comment]
@ChillarAnand @mudassir0909 Can we merge this?

**Comment by mudassir0909** [comment]
The UI of review section is incomplete, I'm waiting for the bootstrap change that I mentioned

**Comment by sivaa** [comment]
@mudassir0909 Okay. Thanks a lot.

**Comment by ChillarAnand** [comment]
@mudassir0909 you can use [this patch]
(https://github.com/ChillarAnand/junction/commit/fa570b465b4645fabd1d1cdeed707b8f61ea4d67.patch) to render review form

**Comment by mudassir0909** [comment]
@sivaa We can merge this now

**Comment by sivaa** [comment]
Thanks.

**Pull request merged**
