### PR TITLE
Fixed empty space at bottom

### LINKED ISSUE #257: empty space at the bottom
in all pages, there is lot of empty space between end of content and the footer. this should be removed.
here is a screenshot
jj

### PR DESCRIPTION
**Pull request by NabeelValapra**
Fix #257

### CODE REVIEW

**Comment by kracekumar** [comment]
But home page image is lost. Can you fix it ?
screen shot 2015-05-30 at 5 23 19 pm

**Comment by NabeelValapra** [comment]
Sorry I didn't thought of it.

**Comment by mudassir0909** [comment]
@NabeelValapra which empty space issue you are trying to fix ? don't see any on http://junction.pybelgaum.org/, do you see it on any specific URL ?

**Comment by mudassir0909** [comment]
and please revert that change, `height: 100%` is required on `html` & `body` tags

**Comment by mudassir0909** [comment]
@NabeelValapra related to my first comment: never mind got it

**Comment by kracekumar** [comment]
@mudassir0909 Now you check https://in.pycon.org/cfp/pycon-india-2015/proposals/

**Comment by mudassir0909** [comment]
there is a style on `footer` which says `top: 100%` we just need to remove that

**Comment by mudassir0909** [comment]
Not able to find that style in this file https://github.com/pythonindia/junction/blob/develop/junction/static/less/base.less But it's on the live, no idea how

**Comment by kracekumar** [comment]
Because of this https://github.com/pythonindia/junction/blob/master/junction/static/css/app.css#L8410 ?

**Comment by kracekumar** [comment]
@mudassir0909 I removed that line in server. Looks like now it is working. I will speak with Vignesh and figure out generation of css files in server.

**Comment by mudassir0909** [comment]
@kracekumar yes it's the same line, this is dangerous because once you run the less compiler it'll replace all the changes you made in css. So, the plan is to make the changes in only LESS files (don't worry if you don't know LESS, you can write normal css in less as well).

**Comment by theskumar** [comment]
> I removed that line in server. Looks like now it is working. I will speak with Vignesh and figure out generation of css files in server.

created #318 with a plausible solution to this issue. (Use django-compressor)

**Pull request merged**
