### PR TITLE
Rewrite contributing guide (and switch to ReST)

### PR DESCRIPTION
**Pull request by pradyunsg**
This is first of multiple PRs for updating the documentation, making it more approachable for first-time contributors and a clearer reference for functionality and development processes.

The change to ReST here, is in line with a discussion about switching over to Sphinx for documentation generation (more on that in another PR).

### CODE REVIEW

**Comment by pradyunsg** [comment]
Dependent on #576 being merged with CI fixes.

**Comment by icyphox** [comment]
It appears that Sphinx [supports Markdown-based docs](https://www.sphinx-doc.org/en/master/usage/markdown.html). Might save you the trouble of having to rewrite everything to ReST.

**Comment by pradyunsg** [comment]
I have set that up here.

> Might save you the trouble of having to rewrite everything to ReST.

I don't really view it as trouble tbh. I'll likely be rewriting big parts of the documentation anyway (see #577 for changes to the "contributing" instructions) so changing to ReST would be okay with me. :)

**Comment by zerothabhishek** [comment]
Markdown is a more popular format, so everyone will want to know why we chose ReST. Its best to add details on the merits of ReST over Markdown somewhere in the documentation. @pradyunsg

**Comment by icyphox** [comment]
@zerothabhishek, agreed. Most of us are familiar with Markdown (intuitive, predictable) and ReST isn't quite as approachable, IMO. So yeah, definitely elaborate on why ReST was chosen.

**Comment by zerothabhishek** [comment]
I think #577 includes code from this PR, right @pradyunsg  ? If so, we'll merge only that one.

**Comment by pradyunsg** [comment]
This file being in ReST allows me to use ReST's `.. include` (in #577) to include this content in the generated documentation pages. This allows to have a single point of truth w.r.t the contributing guide.

I don't think there's any reason to block merging this PR on #577. I'd much more prefer having multiple smaller PRs than having one big PR that does it all, especially if that allows me to iterate faster.

FWIW, I'd probably want to do the same with the Code of Conduct anyway. I'll close this PR and drop this change from #577 for now, let's come back to this later. I don't want to engage in a Markdown vs ReST discussion.

**Comment by pradyunsg** [comment]
I don't mean to come off as rude here, it's just trying to streamline the process. Sorry for not waiting on inputs before closing the PR.

**Pull request closed without merging**
