### PR TITLE
Reviewer identification. #279

### PR DESCRIPTION
**Pull request by theSage21**
Distinct reviewers can be identified without revealing names.

However it might be an issue as the actual PK is used to identify and so
reviewers can be identified across proposals instead of just on one proposal.

### CODE REVIEW

**Comment by kracekumar** [comment]
No we can have separate column called "nick" in reviewers column, which can be manually added from admin for now. Latter we can add programatically. If the nick is empty, we will say "reviewer".

What do you say ?

**Comment by theSage21** [comment]
So instead of saying 'a reviewer[1]' we say '<nick>'. Am I right in understanding this? If this is the case I do not see anything against it. The reviewers must be a handful in number and so if is fine to add via admin.

**Comment by kracekumar** [comment]
Yes, so creative people can give their own name to reviewers.

**Comment by dhilipsiva** [comment]
So should we use use a custom User model to implement this thing?

**Comment by kracekumar** [comment]
No custom user model, we will add that to existing reviewers model only.

**Comment by dhilipsiva** [comment]
Oh dang! I just realized that I asked a very silly question. Got confused! Anyways, we should be adding this to both `ConferenceProposalReviewer` and `ProposalSectionReviewer` right?

**Comment by kracekumar** [comment]
We will have it on `ConferenceProposalReviewer` model alone. Nick on `ProposalSectionReviewer` will lead to more work.

**Comment by kracekumar** [comment]
@theSage21 Can you complete this pull request as per discussions ?

**Comment by theSage21** [comment]
@kracekumar Sorry, I just got back after a series of examinations. I will complete this but it might take a few days.

**Comment by theSage21** [comment]
@kracekumar  When you say
>Yes, so creative people can give their own name to reviewers. 

The people here are multiple. So can the reviewer have multiple nicknames depending on who gave them what nickname? Or am I right in thinking that there is just a single `nick` field on the `ConferenceProposalReviewer`?

**Comment by theSage21** [comment]
Sigh, @kracekumar I have more exams coming up. Someone else should take this up.

**Comment by kracekumar** [comment]
@theSage21 no worries. 

@dhilipsiva Can you take this feature and complete ? Original issue is #279.

**Comment by dhilipsiva** [comment]
Sure thing. My internet connection got severed due to the heavy wind. I
will work on and push the changes when the connection is restored.

**Pull request closed without merging**
