### PR TITLE
Add get conference view to handle /<conference_slug> urls and act accordingly

### LINKED ISSUE #645: Non proposal sub urls are broken
Go to any non proposal url e.g. `/profiles`, it redirects to `/profiles/proposals` . This was introduced in #563. We need to revert the change and come up with the correct fix for the issue.

### PR DESCRIPTION
**Pull request by palnabarun**
Two cases may exist when accessing `/<conference_slug>` :
1. Conference Exists - Redirect to `/<conference_slug>/proposals`
2. Conference Does not exist - Show 404 Page

Fixes #645

### CODE REVIEW

**Comment by palnabarun** [comment]
@ananyo2012 Can you please review this?

**Comment by ananyo2012** [comment]
@palnabarun There is a linter error can you fix that ?

**Comment by ananyo2012** [comment]
@palnabarun This is still causing the issue #645 since any url is being redirected as a conference url. Probably you need to put the url pattern at the very end so that an url will fallback to that if none of the defined urlpatterns match.

**Comment by palnabarun** [comment]
@ananyo2012 That stems from the fact that the root resource in Junction is assumed to be a conference slug.

Ideally, the URL for the conference resource should have been `/conference/<conference_slug>/*` instead of `/<conference_slug>/*`. Using a resource identifier at the root is not a correct way. The other resources are structured correctly.

So, in the current scenario, `/anything-that-the-user-write-shere` is assumed to be a conference slug and checked for.

I would have liked to fix the URL's in the first place. But, it seemed to be a rabbit hole as the whole codebase needs to be searched for hardcoded URL's.

>  Probably you need to put the url pattern at the very end so that an url will fallback to that if none of the defined urlpatterns match.

Will it not still result in a conference found? I am a bit confused here with respect to the expectations. Can you please provide a map of the possible use case that you are thinking?

**Comment by ananyo2012** [comment]
@palnabarun Try going to `/profiles` and you will get a 404 error. `/profiles` lists all proposals submitted by an user. Since we assume that can also be a conference we try to get the corresponding Conference in get_conference and then show a 404 since no such valid conference is present.

> Ideally, the URL for the conference resource should have been `/conference/<conference_slug>/*` instead of `/<conference_slug>/*`. Using a resource identifier at the root is not a correct way. The other resources are structured correctly.
>
I like this solution. We need to see how much impact will it cause to the existing test cases and usability.

**Comment by palnabarun** [comment]
> Try going to /profiles and you will get a 404 error. /profiles lists all proposals submitted by an user. 

Got it.

I see a pattern now of which URL's will help.

**Comment by ananyo2012** [comment]
On second thought having a `/conference/<conference_slug>/` url will mean the cfp absolute url will be `https://n.pycon.org/cfp/conference/<conference_slug>` which is not appropriate. Junction seems to be deployed under `/cfp` url. Maybe past junction maintainers had reasons for designing the urls like that.

**Comment by palnabarun** [comment]
Basic question:
> the cfp absolute url will be https://in.pycon.org/cfp/conference/<conference_slug> which is not appropriate

Why?

---

Let's, not dilly dally on what is there in the present. Maybe they started the routing keeping something in mind and then maybe thought that is not correct but had no way to change things at that point in time. Let's focus on what is correct and suits better.

I couldn't find history and discussion related to the URL convention based on commits.

**Comment by palnabarun** [comment]
Nevertheless, I have reorganized the URL order so that the routing works as expected.

**Comment by pradyunsg** [comment]
LGTM.

Regarding the hardcoded URLs, I'm personally OK to break existing URLs to completely restructure the application's URL structure.

**Pull request merged**
