### PR TITLE
Style the code consistently

### LINKED ISSUE #655: Blacken the code!
Well, it'd make the codebase easier to read IMO.

Plus, it'll help do away with years of different code styles being used in various parts of the codebase.

### PR DESCRIPTION
**Pull request by palnabarun**
`142 files reformatted, 37 files left unchanged`

Fixes #655

### CODE REVIEW

**Comment by palnabarun** [comment]
@pradyunsg Do you want to review? :sweat_smile:

**Comment by pradyunsg** [comment]
Why are you up so late? 😂

**Comment by pradyunsg** [comment]
I really think we want to have a CI check to do this.

I have a draft branch locally, adopting pre-commit, isort, black and a few more useful tools. I'll file a PR when I wake up in the morning.

**Comment by palnabarun** [comment]
> Why are you up so late? :joy:

Good question. :sweat_smile: 

> I really think we want to have a CI check to do this.

Cool.

---

So, this is good to go I guess.

**Comment by ananyo2012** [comment]
I really wish changes like these are multipart so that they are easier to review.

**Comment by palnabarun** [comment]
> I really wish changes like these are multipart so that they are easier to review.

Me too. Although this shouldn't need a review since It is generated by running [black](https://black.readthedocs.io/en/stable/) on the codebase.

But broadly speaking if I have to give you an overview:
1. `'` quoted strings are converted to `"` quoted ones - Most of the changes
2. Line breaks are made saner. - Second most common occurrence

> Also wasn't the code flake8 checked already ?

`flake8` and `pep8` digress in a variety of matters these days. :( For example, https://github.com/python/peps/commit/c59c4376ad233a62ca4b3a6060c81368bd21e85b

**Comment by palnabarun** [comment]
cc @ananyo2012 ^^^

**Comment by palnabarun** [comment]
@ananyo2012 Also, please have a look at this commit https://github.com/pythonindia/junction/pull/656/commits/1aff0a0c453499ce896ed873979d3ebeab77d3eb

**Comment by pradyunsg** [comment]
> this is good to go I guess

No, I strongly suggest that we don't add such broad style changes without enforcement along with them.

**Comment by palnabarun** [comment]
> No, I strongly suggest that we don't add such broad style changes without enforcement along with them.

Enforcement should come and that's why we are here to review pull requests and go forward with them only when functionality, code style, and tests are appropriate.

An automated gatekeeper not being present does not necessarily mean the building should be kept dirty for long.

And the style changes are not broad, they just occur too many times and I spent a lot of time reviewing each hunk of diff to ensure the functionality is not breaking.

**Pull request closed without merging**
